config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'gossips#index'

  resources :gossips
  resources :users
  resources :cities
  resources :comments
  resources :sessions, only: [:new, :create, :destroy]

  resources :gossips do
    resources :comments
  end

# WE USE THE OLD METHOD TO SHOW STATIC PAGES (no need to have index, show, create...)
  get "/team", to: "static_pages#team"
  get "/contact", to: "static_pages#contact"

  # THIS IS THE OLD METHOD, WE'RE NOW USING THE ABOVE METHOD ie: resources
    # get "/", to: "welcome#home"
    # get "/welcome/:id", to: "welcome#greet"
    # get "/gossip/:id", to: "gossip#show"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  has_many :likes, :as => :likeable, dependent: :destroy
  has_many :comments, :as => :commentable, dependent: :destroy
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  include SessionsHelper
  before_action :authenticate_user, only: [:index, :show, :create, :new]
  def new
    @comment = Comment.new
    @gossip = Gossip.find(params[:gossip_id])

    puts "n" * 100
  end

  def create
    @user = current_user

    @gossip = Gossip.find(params[:gossip_id])

    # @gossip = Gossip.create(:user => User.all.sample, :title => params[:title], :content => params[:content])
    # redirect_to root_path
      #@comment = Comment.new(:user_id => User.all.sample, :commentable_type => "Gossip", :commentable_id => params[:gossip_id], :content => params[:content]) # avec xxx qui sont les données obtenues à partir du formulaire
      @comment = Comment.new(:user => @user, :commentable => @gossip, :content => params[:content])
      if @comment.save # essaie de sauvegarder en base @gossip
        redirect_to gossip_path(@gossip.id) # si ça marche, il redirige vers la page d'index du site
      else
        # sinon, il render la view new (qui est celle sur laquelle on est déjà)
        render new_gossip_path
      end
  end

  def edit
    @comment = Comment.find(params[:id])
    @gossip = Gossip.find(params[:gossip_id])

  end

def update
  puts "$" * 100
  puts @gossip
  puts "$" * 100
  @comment = Comment.find(params[:id])
  comment_params = params.require(:comment).permit(:content)
   if @comment.update(comment_params)
      redirect_to root_path
  else
      render :edit
  end
  # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
  # pour info, le contenu de ce formulaire sera accessible dans le hash params
  # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
end

private

def authenticate_user
  unless current_user
    flash[:danger] = "Please log in."
    redirect_to new_session_path
  end
end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/edit.html.erb
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4">View Gossip</h1>
  <p class="lead">Here's a juicy gossip for you. Enjoy!</p>
</div>

<br>

<div class="container">
<div class="card">
  <h5 class="card-header">
    <a <%= link_to "#{@gossip.user.first_name}", user_path(@gossip.user.id) %> • <%= link_to "#{@gossip.user.city.name}", city_path(@gossip.user.city.id) %> </a>
  </h5>
    <div class="card-body">
      <h5 class="card-title"><%= @gossip.title %> </h5>
      <p class="card-text"><%= @gossip.content %></p>
      <a <%= link_to "Edit", edit_gossip_path(@gossip.id), :class => "btn btn-outline-primary" %> </a>
      <a <%= link_to "Delete", gossip_path(@gossip.id), :class => "btn btn-outline-danger", :method => :delete%> </a>
      <a <%= link_to "Comment", new_gossip_comment_path(@gossip.id), :class => "btn btn-outline-primary" %> </a>


    </div>
  </div>
</div>
</div>

<br>

<div class="container">
  <div class="container">
  <% @gossip.comments.each do |n| %>
  <% if n.id != params[:id].to_i %>
  <div class="card">
    <div class="card-body">
      <h5 class="card-title"><%= n.user.first_name %></h5>
      <p class="card-text"><%= n.content %> </p>
      <div>
      <a <%= link_to "Edit", edit_gossip_comment_path(@gossip.id, n.id), :class => "btn btn-outline-primary" %> </a>
    </div>
    </div>
  </div> <br>
  <% else %>
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"> <%= n.user.first_name %> • Edit Comment </h5>
            <%= form_for @comment do |f| %>
            <div class="form-group">
              <%= f.text_area :content, class: 'form-control' %>
            </div>
            <div class="form-group">
              <button type="submit"class="btn btn-primary">Update</button>
            </div>
              <% end %>
          </div>
    </div> <br>
  <% end %>
  <% end %>
</div>
</div>

app/views/comments/new.html.erb
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4">View Gossip</h1>
  <p class="lead">Here's a juicy gossip for you. Enjoy!</p>
</div>

<br>

<div class="container">
<div class="card">
  <h5 class="card-header">
    <a <%= link_to "#{@gossip.user.first_name}", user_path(@gossip.user.id) %> • <%= link_to "#{@gossip.user.city.name}", city_path(@gossip.user.city.id) %> </a>
  </h5>
    <div class="card-body">
      <h5 class="card-title"><%= @gossip.title %> </h5>
      <p class="card-text"><%= @gossip.content %></p>
      <a <%= link_to "Edit", edit_gossip_path(@gossip.id), :class => "btn btn-outline-primary" %> </a>
      <a <%= link_to "Delete", gossip_path(@gossip.id), :class => "btn btn-outline-danger", :method => :delete%> </a>
      <a <%= link_to "Comment", new_gossip_comment_path(@gossip.id), :class => "btn btn-outline-primary" %> </a>


    </div>
  </div>
</div>
</div>

<br>

<div class="container">
  <div class="row">
    <div class="col-sm-8">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Add a Comment</h5>
          <%= form_tag gossip_comments_path do %>
          <div class="form-group">
            <%= text_area_tag :content, placeholder = "Add a comment here...", class: 'form-control no-border' %>
          </div>
            <%= submit_tag "Comment", class: 'btn btn-default btn btn-primary' %>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<br>

<div class="container">
  <div class="container">
  <% @gossip.comments.each do |n| %>
  <div class="media">
    <!-- <%= image_tag "user.png", :size => "20x20" %> -->
    <div class="media-body">
      <h5 class="mt-0"><%= n.user.first_name %></h5>
      <%= n.content %>
    </div>
  </div> <br>
  <% end %>
</div>
</div>