config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'gossips#index'

  resources :gossips
  resources :users
  resources :cities
  resources :comments
  resources :sessions, only: [:new, :create, :destroy]

  resources :gossips do
    resources :comments
  end

# WE USE THE OLD METHOD TO SHOW STATIC PAGES (no need to have index, show, create...)
  get "/team", to: "static_pages#team"
  get "/contact", to: "static_pages#contact"

  # THIS IS THE OLD METHOD, WE'RE NOW USING THE ABOVE METHOD ie: resources
    # get "/", to: "welcome#home"
    # get "/welcome/:id", to: "welcome#greet"
    # get "/gossip/:id", to: "gossip#show"
end

app/models/user.rb
class User < ApplicationRecord
  
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  belongs_to :city
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :join_table_message_recipients
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "JoinTableMessageRecipient"
  has_many :likes
  has_many :comments
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
    puts "user show" * 10
    @user = User.find(params[:id])
  end

  def new
    puts "user new" * 10
    #@user = User.new
  end

  def create
    puts "user create" * 10
    u = User.new
    u.email = params[:email]
    u.first_name = params[:first_name]
    u.password = params[:password]
    u.city_id = City.all.sample.id
    u.save

  # Redirect to root_path with stored session id
   session[:user_id] = u.id
   redirect_to root_path


    # a = City.find_by(:name => params[:city])
    # puts "@" * 100
    # puts a.blank?
    # puts "@" * 100

    # if a.blank? == true
    #   puts "@" * 100
    #   puts "C'est BLANK"
    #   puts "@" * 100
    #   City.create(:name => params[:city])
    #   a2 = City.find_by(:name => params[:city]).id
    #   u.city_id = a2
    # else
    #   puts "@" * 100
    #   puts "C'est PAS BLANK"
    #   puts "@" * 100
    #   a = City.find_by(:name => params[:city]).id
    #   puts "#" * 100
    #   puts a
    #   puts "#" * 100
    #   u.city_id = a
    #   u.save
    # end
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4">Create Account</h1>
</div>

<br>

<div class="container">
  <%= form_tag users_path do %>
  <div class="form-group">
    <%= text_field_tag :city, placeholder = "City", class: 'form-control', autofocus: true %>
  </div>
  <div class="form-group">
    <%= text_field_tag :first_name, placeholder = "First Name", class: 'form-control', autofocus: true %>
  </div>
  <div class="form-group">
    <%= text_field_tag :email, placeholder = "Email", class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= text_field_tag :password, placeholder = "Password (minimum of 6 caracters)", class: 'form-control' %>
  </div>
  <%= submit_tag "Submit", class: 'btn btn-default btn btn-success' %>
</div>
<% end %>

app/views/users/show.html.erb
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4"><%= @user.first_name %> <%= @user.last_name %></h1>
  <p class="lead">View gossiper profils here.</p>
</div>

<br>

<div class="container">
<div class="card">
  <h5 class="card-header">
    <%= @user.first_name %> <%= @user.last_name %>
  </h5>
  <div class="card-body">
    <p class="card-text"><%= @user.description %></p>
    <li> email: <%= @user.email %> </li>
    <li> age: <%= @user.age %> </li>
    <li>  city: <%= @user.city.name %> </li>
    <li> <%= link_to "#{@user.city.name}", city_path(@user.city.id) %> </li>
  </div>
</div>
</div>